version: '0.0.2.{build}'

image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - BuildDebug
  - BuildRelease
  - Debug
  - Release

cache:
  - $(APPVEYOR_BUILD_FOLDER)\BuildDebug
  - $(APPVEYOR_BUILD_FOLDER)\BuildRelease
  - $(APPVEYOR_BUILD_FOLDER)\x64\BuildDebug
  - $(APPVEYOR_BUILD_FOLDER)\x64\BuildRelease

build:
  project: Space.sln

test_script:
  - copy .\$(configuration)\UnitTest.exe .\Source\UnitTest\UnitTest\UnitTest$(configuration).exe && .\Source\UnitTest\UnitTest\UnitTest$(configuration).exe -all