version: '0.0.2.{build}'

image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - BuildDebug
  - BuildRelease
  - Debug
  - Release

build:
  project: Space.sln

test_script:
  - copy .\%CONFIGURATION%\UnitTest.exe .\Source\UnitTest\UnitTest\UnitTest%CONFIGURATION%.exe && .\Source\UnitTest\UnitTest\UnitTest%CONFIGURATION%.exe -all